global:
  resolve_timeout: 5m

route:
  receiver: 'webhook'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://webhook:8000/webhook'
        send_resolved: true
